name: PR Tester

on:
  issue_comment:
    types: [created]

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check for comment triggers
        if: ${{ github.event_name == 'issue_comment' }}
        uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'run cypress tests please'
      - name: Get tag expressions from comment
        if: steps.check.outputs.triggered == 'true'
        uses: actions/github-script@v3
        id: tag-expression
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commentBody = context.payload.comment.body
            if (commentBody.includes("tags")) {
              const tagPattern = /@[A-Za-z]+/g
              const commentParts = commentBody.split("tags")
              const tagExpression = commentParts[1].match(tagPattern) ? commentParts[1].trim() : ""
              core.info(`tag expression: "${tagExpression}"`)
              return tagExpression
            }
      - name: Get branch name
        if: github.event.issue.pull_request
        uses: actions/github-script@v3
        id: get-pr
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
            # - name: Run Cypress tests on CircleCI
            #   if: steps.check.outputs.triggered == 'true'
            #   uses: joelwmale/webhook-action@master
            #   with:
            #     url: "https://circleci.com/api/v1.1/project/gh/${{ github.repository }}/tree/${{ fromJSON(steps.get-pr.outputs.result).head.ref }}"
            #     headers: '{"circle-token": "${{ secrets.CIRCLECI_TOKEN }}"}'
            #     body: '{"build_parameters": { "CIRCLE_JOB": "e2e_ci_block_on_fail", "CYPRESS_ENVIRONMENT": "staging", "TAG_EXPRESSION": ${{ steps.tag-expression.output }}}}'
